export const AUTHORIZE_CLIENT = "AUTHORIZE_CLIENT";
export const CONNECT_CLIENT = "CONNECT_CLIENT";
export const SET_TOKEN = "SET_TOKEN";

export const ENABLE_DEV_MODE = "ENABLE_DEV_MODE";
export const DISABLE_DEV_MODE = "DISABLE_DEV_MODE";

export const ITEMS_QUERY_REQUEST = "ITEMS_QUERY_REQUEST";
export const ITEMS_QUERY_SUCCESS = "ITEMS_QUERY_SUCCESS";
export const ITEMS_QUERY_FAILURE = "ITEMS_QUERY_FAILURE";

export const SUB_ITEMS_QUERY_REQUEST = "SUB_ITEMS_QUERY_REQUEST";
export const SUB_ITEMS_QUERY_SUCCESS = "SUB_ITEMS_QUERY_SUCCESS";
export const SUB_ITEMS_QUERY_FAILURE = "SUB_ITEMS_QUERY_FAILURE";
